[package]
name = "viture-one-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
viture-one-sdk-sys = {path="../viture-one-sdk-sys"}
